[package]
name = "noir"
type = "bin"
authors = [""]

[dependencies]
aes  = { tag = "v0.5.0", git = "https://github.com/TaceoLabs/noir-aes" }
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }