[package]
name = "sha_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.3", default-features = false, features = ['std'] }
hex = "0.4"
chacha20poly1305 = "0.10"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }